### ISSUE TITLE
Замечания по lw1

### ISSUE THREAD

**Issue by ivklgn** [dmitrynjg/lab1#1]
комментарий коммита должен отражать суть изменений
https://github.com/lulldev/webdev/blob/master/coding-convections/git.md

**Comment by ivklgn** [comment]
- нарушен coding-convention - количество отступов

- в css файле не стоит разделять стили внутри класса

```css
.product-entry img{

  width: 100px; 

  max-width: 600px; 

  height: auto; 

  margin-bottom: 20px; 

  display: block;
}
```

- поправить разделение `{` и `,`

**Comment by ivklgn** [comment]
`bg_white`, `product-info` - нужно определится со стилем именования.

**Comment by ivklgn** [comment]
```css
.bg_light {
  background: #f7fafa;
}

.bg_black {
  background: #000000;
}

.bg_dark {
  background: rgba(0, 0, 0, .8);
}
```

подобные стили в html коде не используются. проверьте css классы
